import re
import requests
import os

def download_missing_usd(text, download_folder="."):
    base_url = "https://omniverse-content-production.s3-us-west-2.amazonaws.com/Assets/Isaac/4.5/Isaac/Environments/Office/Props/"

    # USD 파일명 추출
    match = re.search(r'Could not open asset.*?/(\w+\.usd)', text)
    if not match:
        print("USD 파일명을 찾을 수 없습니다.")
        return False

    usd_filename = match.group(1)
    download_url = base_url + usd_filename

    # 다운로드 경로 설정
    local_filepath = os.path.join(download_folder, usd_filename)

    if os.path.exists(local_filepath):
        print("file exist.")
        return True

    # 파일 다운로드
    response = requests.get(download_url)
    if response.status_code == 200:
        with open(local_filepath, 'wb') as file:
            file.write(response.content)
        print(f"{usd_filename} 파일이 성공적으로 다운로드되었습니다: {local_filepath}")
        return True
    else:
        print(f"파일 다운로드 실패: {download_url} (상태코드: {response.status_code})")
        return False


log = """2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorB_WC_man_982/SM_DoorB_Door/SM_WC_man>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_WC_man.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorB_WC_man_982/SM_DoorB_Door/SM_WC_man>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase2/InstancedBP_PaperCase2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_Case.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase2/InstancedBP_PaperCase2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorB_WC_woman_542/SM_DoorB_Door/SM_WC_woman>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_WC_woman.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorB_WC_woman_542/SM_DoorB_Door/SM_WC_woman>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase2/SM_PaperCase_door_R/SM_PaperCase_glass_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_glass_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase2/SM_PaperCase_door_R/SM_PaperCase_glass_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorMrSmith_3041/SM_DoorA_Door/SM_PlateMrSmith>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PlateMrSmith.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorMrSmith_3041/SM_DoorA_Door/SM_PlateMrSmith>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase_822/SM_PaperCase_door_R/SM_PaperCase_glass_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_glass_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase_822/SM_PaperCase_door_R/SM_PaperCase_glass_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_155/SM_DoorB_Door/SM_DoorB_Handle>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_Handle_142.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_155/SM_DoorB_Door/SM_DoorB_Handle>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC2_431/SM_DoorB_Door/SM_DoorB_Handle>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_Handle_142.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC2_431/SM_DoorB_Door/SM_DoorB_Handle>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorEntrance_2651/SM_DoorEntrance_glass_main_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorEntrance_glass_main.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorEntrance_2651/SM_DoorEntrance_glass_main_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase_822/InstancedBP_PaperCase_822>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_Case.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase_822/InstancedBP_PaperCase_822>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase_822/SM_PaperCase_door_L/SM_PaperCase_glass_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_glass_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase_822/SM_PaperCase_door_L/SM_PaperCase_glass_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase2/SM_PaperCase_door_R/InstancedSM_PaperCase_door_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_door_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase2/SM_PaperCase_door_R/InstancedSM_PaperCase_door_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorEntrance_2651/SM_DoorEntrance_glass_main_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorEntrance_glass_main.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorEntrance_2651/SM_DoorEntrance_glass_main_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase_822/SM_PaperCase_door_R/InstancedSM_PaperCase_door_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_door_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase_822/SM_PaperCase_door_R/InstancedSM_PaperCase_door_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC2_431/SM_DoorB_Door/InstancedSM_DoorB_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_Door_141.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC2_431/SM_DoorB_Door/InstancedSM_DoorB_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_155/InstancedBP_DoorC_155>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_140.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_155/InstancedBP_DoorC_155>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC2_431/InstancedBP_DoorC2_431>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_140.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC2_431/InstancedBP_DoorC2_431>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_R/SM_DoorEntrance_glass_door_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorEntrance_glass_door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_R/SM_DoorEntrance_glass_door_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_155/SM_DoorB_Door/InstancedSM_DoorB_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_Door_141.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_155/SM_DoorB_Door/InstancedSM_DoorB_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_R/InstancedSM_DoorEntrance_door_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorEntrance_door_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_R/InstancedSM_DoorEntrance_door_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase_822/SM_PaperCase_door_L/InstancedSM_PaperCase_door_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_door_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase_822/SM_PaperCase_door_L/InstancedSM_PaperCase_door_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase2/SM_PaperCase_door_L/SM_PaperCase_glass_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_glass_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase2/SM_PaperCase_door_L/SM_PaperCase_glass_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_L/SM_DoorEntrance_glass_door_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorEntrance_glass_door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_L/SM_DoorEntrance_glass_door_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_L/InstancedSM_DoorEntrance_door_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorEntrance_door_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorEntrance_2651/SM_DoorEntrance_door_L/InstancedSM_DoorEntrance_door_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_Security_350/InstancedBP_DoorC_Security_350>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_140.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_Security_350/InstancedBP_DoorC_Security_350>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PaperCase2/SM_PaperCase_door_L/InstancedSM_PaperCase_door_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PaperCase_door_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PaperCase2/SM_PaperCase_door_L/InstancedSM_PaperCase_door_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_Security_350/SM_DoorB_Door/InstancedSM_DoorB_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_Door_141.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_Security_350/SM_DoorB_Door/InstancedSM_DoorB_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_Security_350/SM_DoorB_Door/SM_PlateSecurity>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PlateSecurity.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_Security_350/SM_DoorB_Door/SM_PlateSecurity>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorGlassDecor_250cm2/SM_DoorGlassDecor_250cm_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorGlassDecor_250cm_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorGlassDecor_250cm2/SM_DoorGlassDecor_250cm_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorGlassDecor_250cm_368/SM_DoorGlassDecor_250cm_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorGlassDecor_250cm_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorGlassDecor_250cm_368/SM_DoorGlassDecor_250cm_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorC_Security_350/SM_DoorB_Door/SM_DoorB_Handle>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorB_Handle_142.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorC_Security_350/SM_DoorB_Door/SM_DoorB_Handle>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorGlassDecor_250cm2/InstancedBP_DoorGlassDecor_250cm2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorGlassDecor_250cm.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorGlassDecor_250cm2/InstancedBP_DoorGlassDecor_250cm2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorGlassDecor_250cm_368/SM_DoorGlassDecor_250cm_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorGlassDecor_250cm_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorGlassDecor_250cm_368/SM_DoorGlassDecor_250cm_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor2_368/SM_PanicDoor_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor2_368/SM_PanicDoor_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor6/SM_PanicDoor_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor6/SM_PanicDoor_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorGlassDecor_250cm2/SM_DoorGlassDecor_250cm_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorGlassDecor_250cm_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorGlassDecor_250cm2/SM_DoorGlassDecor_250cm_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor_347/SM_PanicDoor_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor_347/SM_PanicDoor_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor4/SM_PanicDoor_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor4/SM_PanicDoor_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor5/InstancedBP_PanicDoor5>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor5/InstancedBP_PanicDoor5>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor6/SM_PanicDoor_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor6/SM_PanicDoor_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor2_368/SM_PanicDoor_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor2_368/SM_PanicDoor_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor6/InstancedBP_PanicDoor6>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor6/InstancedBP_PanicDoor6>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor2_368/InstancedBP_PanicDoor2_368>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor2_368/InstancedBP_PanicDoor2_368>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DoorGlassDecor_250cm_368/InstancedBP_DoorGlassDecor_250cm_368>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DoorGlassDecor_250cm.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DoorGlassDecor_250cm_368/InstancedBP_DoorGlassDecor_250cm_368>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor5/SM_PanicDoor_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor5/SM_PanicDoor_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor5/SM_PanicDoor_R>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_R.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor5/SM_PanicDoor_R>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor4/InstancedBP_PanicDoor4>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor4/InstancedBP_PanicDoor4>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor_347/SM_PanicDoor_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor_347/SM_PanicDoor_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor_347/InstancedBP_PanicDoor_347>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor_347/InstancedBP_PanicDoor_347>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor11/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor11/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor10/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor10/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_PanicDoor4/SM_PanicDoor_L>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_PanicDoor_L.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_PanicDoor4/SM_PanicDoor_L>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor12/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor12/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor13/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor13/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor5/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor5/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor6/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor6/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor7/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor7/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor8/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor8/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor9_222/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor9_222/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor3/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door_144.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor3/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,208ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor13/InstancedBP_ToiletDoor13>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor13/InstancedBP_ToiletDoor13>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor2/InstancedBP_ToiletDoor2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_143.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor2/InstancedBP_ToiletDoor2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor2/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door_144.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor2/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor11/InstancedBP_ToiletDoor11>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor11/InstancedBP_ToiletDoor11>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor5/InstancedBP_ToiletDoor5>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor5/InstancedBP_ToiletDoor5>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor6/InstancedBP_ToiletDoor6>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor6/InstancedBP_ToiletDoor6>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor12/InstancedBP_ToiletDoor12>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor12/InstancedBP_ToiletDoor12>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor3/InstancedBP_ToiletDoor3>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_143.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor3/InstancedBP_ToiletDoor3>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor_511/InstancedBP_ToiletDoor_511>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_143.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor_511/InstancedBP_ToiletDoor_511>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor10/InstancedBP_ToiletDoor10>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor10/InstancedBP_ToiletDoor10>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor4/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door_144.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor4/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor4/InstancedBP_ToiletDoor4>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_143.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor4/InstancedBP_ToiletDoor4>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor_511/SM_ToiletDoor_Door>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor_Door_144.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor_511/SM_ToiletDoor_Door>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor8/InstancedBP_ToiletDoor8>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor8/InstancedBP_ToiletDoor8>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor7/InstancedBP_ToiletDoor7>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor7/InstancedBP_ToiletDoor7>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_ToiletDoor9_222/InstancedBP_ToiletDoor9_222>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ToiletDoor.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_ToiletDoor9_222/InstancedBP_ToiletDoor9_222>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B3/InstancedBP_Clock_B3>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B3/InstancedBP_Clock_B3>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B2/InstancedBP_Clock_B2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B2/InstancedBP_Clock_B2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B4/InstancedBP_Clock_B4>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B4/InstancedBP_Clock_B4>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B8/InstancedBP_Clock_B8>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B8/InstancedBP_Clock_B8>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B6_2833/InstancedBP_Clock_B6_2833>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B6_2833/InstancedBP_Clock_B6_2833>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B5/InstancedBP_Clock_B5>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B5/InstancedBP_Clock_B5>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B_478/InstancedBP_Clock_B_478>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B_478/InstancedBP_Clock_B_478>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Clock_B7/InstancedBP_Clock_B7>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Clock_B.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Clock_B7/InstancedBP_Clock_B7>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_frame4/SK_Elevator_doors_outside>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SK_Elevator_doors_outside.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_frame4/SK_Elevator_doors_outside>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_frame2/InstancedBP_Elevator_frame2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Elevator_frame.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_frame2/InstancedBP_Elevator_frame2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_frame2/SK_Elevator_doors_outside>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SK_Elevator_doors_outside.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_frame2/SK_Elevator_doors_outside>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Frame_Floor1/SK_DoorsOutside_Floor1>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SK_Elevator_doors_outside.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Frame_Floor1/SK_DoorsOutside_Floor1>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Frame_Floor1/InstancedSM_Frame_Floor1>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Elevator_frame.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Frame_Floor1/InstancedSM_Frame_Floor1>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_frame4/InstancedBP_Elevator_frame4>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Elevator_frame.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_frame4/InstancedBP_Elevator_frame4>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Frame_Floor2/SK_DoorsOutside_Floor2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SK_Elevator_doors_outside.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Frame_Floor2/SK_DoorsOutside_Floor2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Elevator/InstancedSM_Elevator>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Elevator.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Elevator/InstancedSM_Elevator>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_DrinksMachine_5504/InstancedBP_DrinksMachine_5504>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_DrinksMachine.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_DrinksMachine_5504/InstancedBP_DrinksMachine_5504>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Frame_Floor2/InstancedSM_Frame_Floor2>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_Elevator_frame.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Frame_Floor2/InstancedSM_Frame_Floor2>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Elevator/SK_Elevator_doors_inside>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SK_Elevator_doors_inside.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Elevator/SK_Elevator_doors_inside>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/BP_Elevator_162/SM_Elevator/SK_Elevator_doors_inside>: Could not open asset @/home/do/Desktop/isaac_sim_robot_simul/office/Animations/SK_Elevator_doors_inside_Anim.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@</Root/BP_Elevator_162/SM_Elevator/SK_Elevator_doors_inside>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/Cube37/Cube>: Could not open asset @Cube.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/Props/Cube_147.usd@</Root/Cube>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/SM_BooksSet_467/SM_BooksSet_11>: Could not open asset @SM_BooksSet_11.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_BooksSet_11_167.usd@</Root/SM_BooksSet_11>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)

2025-04-15 04:21:50 [6,646,209ms] [Warning] [omni.usd] Warning (secondary thread): in _ReportErrors at line 2890 of /builds/omniverse/usd-ci/USD/pxr/usd/usd/stage.cpp -- In </Root/SM_ChairOffice_A33/SM_ChairOffice_A>: Could not open asset @SM_ChairOffice_A.usd@ for reference introduced by @/home/do/Desktop/isaac_sim_robot_simul/office/Props/SM_ChairOffice_A_184.usd@</Root/SM_ChairOffice_A>. (instantiating stage on stage @/home/do/Desktop/isaac_sim_robot_simul/office/office.usd@ <0x7f2e68031c30>)"""


input_texts = log.split("\n\n")
success = 0
for i in range(len(input_texts)):
    print(f"#{i} : ",end="")
    if download_missing_usd(input_texts[i], download_folder="./office/Props"):
        success +=1
print(f"Success : {success}, Fail : {len(input_texts)-success}")